version: "3.8"

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PORT=4000
      - MONGO_DB=mongodb://root:example@mongo:27017/socialapp?authSource=admin
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    volumes:
      - ./Server/public/images:/app/public/images
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
